% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{1}

\aufgabe{PDP and ICE in case of interactions}{
	<<child="ex_rnw/ex_pdpinteractions.Rnw">>=
	@
}

\dlz

\aufgabe{ALE}{
	<<child="ex_rnw/ex_R_ale.Rnw">>=
	@
}

\aufgabe{Categorical ALE}{
	<<child="ex_rnw/ex_catale.Rnw">>=
	@
}