% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/ml-trees.tex}
\input{../../latex-math/basic-ml.tex}

\kopfic{4}


\aufgabe{}{
<<child="ex_rnw/quiz.Rnw">>=
@
}

\dlz

\aufgabe{}{
<<child="ex_rnw/ex_faithfulness.Rnw">>=
@
}

\dlz

\aufgabe{}{
<<child="ex_rnw/ex_multiplecfexp.Rnw">>=
@
}