% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{4}


\loesung{Gower Distance}{
	<<child="ex_rnw/sol_gowerdistance.Rnw">>=
	@
}

\dlz

\loesung{LIME}{
	<<child="ex_rnw/sol_R_lime.Rnw">>=
	@
}

\loesung{Counterfactuals - WhatIf}{
	<<child="ex_rnw/sol_R_whatif.Rnw">>=
	@
}