\documentclass[a4paper]{article}

\input{../../style/preamble_ueb.tex}
\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\begin{document}
\kopf{1}

\input{ex_tex/sol_pdpinteractions.tex}

\dlz

% \loesung{
% <<child="ex_rnw/sol_R_ale.Rnw">>=
% @
% }
% 
% \dlz
% 
% \loesung{
% 	<<child="ex_rnw/sol_catale.Rnw">>=
% 	@
% }
\end{document}