---
title: "Exercise Sheet 8: Shapley Values"
output:
  pdf_document: default
  html_document: default
---

# Exercise 1: The Shapley Value

### Libraries
```{r}
library(sets)
library(dplyr)
library(randomForest)
library(combinat)

set.seed(123456)
```


## 1a)
```{r}
### Define the payoff function.
payoff <- function(coalition) {
  ### Define boolean variables that indicate whether Timnit, Margret, Samy, Jeff
  ### and Larry are in the set or not.
  t <- 't' %in% coalition
  s <- 's' %in% coalition
  m <- 'm' %in% coalition
  j <- 'j' %in% coalition
  l <- 'l' %in% coalition

  ### Definition of the payoff as given in the task.
  10*t + 10*m + 10*s + 2*j + 20*(t & m) + 20*(t & m & s) - 30*((t | m | s) & j)
}

### Testing
population <- c('j', 'l', 'm', 's', 't')
payoff(c('t','m'))
payoff(c('t','j','s'))
payoff(c())
payoff(population)
```

## 1b)
```{r}
# https://www.rdocumentation.org/packages/methods/versions/3.6.2/topics/setClass
# https://www.rdocumentation.org/packages/sets/versions/1.0-25/topics/set
# all_unique_subsets_2 <- function(population) {
#   if (length(population) == 0) {
#     return(set(set()))
#   } else {
#     population <- population[!duplicated(population)] # Remove double elements
#     subsets_wo_member <- all_unique_subsets(population[-c(1)])
#     subsets_w_member <- sapply(subsets_wo_member, function(s){
#       set_union(s, set(population[1]))
#     })
#     return(set_union(subsets_wo_member, subsets_w_member))
#   }
# }

all_unique_subsets <- function(population) {
    ### Use built-in set_power function and convert to a list for further processing.
    as.list(set_power(population))
}

### Testing
print(all_unique_subsets(c()))
# as.list(all_unique_subsets_2(c()))
print(all_unique_subsets(c(2)))
# as.list(all_unique_subsets_2(c(2)))
print(all_unique_subsets(c(2,4)))
# as.list(all_unique_subsets_2(c(2,4)))
print(all_unique_subsets(population))
# as.list(all_unique_subsets_2(population))
```

## Definition of useful functions, used several times below
```{r}
### Define a function which returns a list of all possible
  ### coalitions (represented as sets) without (one or more) specific members.
all_coalitions_without_members <- function(members, population) {
  ### Get all players except the member players.
  population_without_members <- setdiff(population, members)

  ### Get all sets of players without the member players.
  as.list(all_unique_subsets(population_without_members))
}

### Define a payoff difference function (which will be useful for several
  ### subtasks. The v_function argument will be helpful for checking the additivity
  ### property in task 1c).
payoff_diff <- function(member, coalition, v_function=payoff) {
  v_function(c(member, coalition)) - v_function(coalition)
}

### Define a function that calculates the payoff differences given a list of
  ### coalitions (which will be useful for several subtasks. The v_function argument
  ### will be helpful for checking the additivity property in task 1c)).
payoff_diff_list <- function(member, coalitions, v_function=payoff) {
  sapply(1:length(coalitions), function(i) payoff_diff(member, coalitions[[i]], v_function))
}
```

## 1b) (continued)
```{r}
### Calculate the Shapley value for a player using the set definition according to
  ### the formula given in the lecture or in chapter 17 of Christoph Molnar's
  ### book Interpretable Machine Learning
  ### (https://christophm.github.io/interpretable-ml-book/shapley.html#definition).
  ### Input: the set of all players and the value function (this will
  ### be helpful for checking the additivity property in task 1c)
shapley_set <- function(member, population, v_function=payoff) {
  population <- population[!duplicated(population)] # Remove double elements
  all_coalitions_without_member <- all_coalitions_without_members(member, population)

  ### For this, compute the payoff differences with and without the member player for all
  ### coalitions at once.
  payoff_diffs <- payoff_diff_list(member, all_coalitions_without_member, v_function)
  
  #### Calculate the weights which are the combinatorical number of occurrences  
  ### of each set.
  F <- length(population)
  weights <- sapply(1:length(all_coalitions_without_member), function(i) {
    cardinality_coalition <- length(all_coalitions_without_member[[i]])
    factorial(cardinality_coalition) * factorial(F - cardinality_coalition - 1) / factorial(F)
  })
  
  #### The Shapley value now is the weighted sum of the differences.
  sum(weights * payoff_diffs)
}
```

```{r}
### Show the result.
print(shapley_set("t", population))
```

## Another helper function for calculating all Shapley values

```{r}
### Define a function that returns all Shapley values for a given population
  ### (which will be useful for several subtasks. The v_function argument will be
  ### helpful for checking the additivity property in task 1c))
all_shapley_values <- function(population, shapley_fct, v_function=payoff) {
  sapply(1:length(population), function(i) shapley_fct(population[i], population, v_function))
}

shapley_test <- function(population, shapley_fct, v_function=payoff) {
  shapley_values <- all_shapley_values(population, shapley_fct, v_function)
  print(shapley_values)
  sum_ <- sum(shapley_values)
  print(sum_)
  print(v_function(population))
  print(sum_ == v_function(population))
}
```

```{r}
### Testing
shapley_test(population, shapley_set)
```

## 1c)
```{r}
### Calculate a Shapley value using the the permutation based definition.
shapley_perm <- function(member, population, v_function=payoff) {
  ### Generate all permutations from the population (as list of vectors).
  all_perms <- combinat::permn(population)

  ### Find the index of the member player for every permutation.
  member_idxs <- sapply(all_perms, function(x) match(member, x))

  ### Get the coalition for each permutation (which are just all the players with
  ### an index lower than the member player).
  coalitions <- lapply(1:factorial(length(population)), function(i) all_perms[[i]][1:member_idxs[i] - 1])

  ### Estimate the Shapley value according to the order definition formula given
  ### in the lecture. This is just the mean of all the payoff differences.
  differences <- payoff_diff_list(member, coalitions, v_function)
  mean(differences)
}
```

```{r}
### Testing
shapley_test(population, shapley_perm)
```

## 1d)
```{r}
### Calculate the permutation based approximation of the Shapley value with  
  ### num_iter iterations.
shapley_perm_approx <- function(member, population, v_function=payoff, num_iter=100) {
  ### Sample num_iter permutations from the population (the single columns are the permutations).
  perms <- replicate(num_iter, sample(population))
  
  ### Find the index of the member player for every permutation (so in every column,
  ### that´s what the 2 is indicating).
  member_idxs <- apply(perms, 2, function(x) match(member, x))
  
  ### Get the coalition for each permutation (which are just all the players with  
  ### an index lower than the member player).
  ### They are now saved in a list with the length being the number of iterations.
  coalitions <- lapply(1:num_iter, function(i) perms[1:member_idxs[i] - 1, i])
  
  ### Estimate the Shapley value according to the algorithm given in the lecture or
  ### in chapter 17 of Christoph Molnar's book Interpretable Machine Learning
  ### (https://christophm.github.io/interpretable-ml-book/shapley.html#estimating-shapley-values).
  ### This is just the arithmetic mean of the payoff differences 
  ### over all sampled coalitions, same as for the exact order definition.
  differences <- payoff_diff_list(member, coalitions,v_function)
  mean(differences)
}
```

```{r}
### Show the result.
print(shapley_perm_approx('t', population, num_iter=1000))
### Not too bad an estimate compared to the result from tasks b) and c).
### Further Testing
for (i in 3:4) {
  print(shapley_perm_approx('t', population, num_iter=10**i))
}
shapley_test(population, shapley_perm_approx)
for (member in population) {
  print(shapley_perm_approx(member, population, num_iter=10**4))
}
```

The exact numbers here depend of course on the specific parameters, the seed ...

## 1e)
### Symmetry Check
```{r}
### Check the symmetry property of the Shapley value as defined in the lecture or  
  ### in chapter 17 of Christoph Molnar's book Interpretable Machine Learning  
  ### (https://christophm.github.io/interpretable-ml-book/shapley.html#definition).
symmetry_check <- function(j, k, population) {
  all_coalitions_without_candidates <- all_coalitions_without_members(c(j, k), population)
  
  ### Calculate the payoff differences for all possible coalitions including j  
  ### (but excluding k) and for all possible coalitions including k (but excluding j).
  payoff_diff_j <- payoff_diff_list(j, all_coalitions_without_candidates)
  payoff_diff_k <- payoff_diff_list(k, all_coalitions_without_candidates)
  
  ### This logical statement now checks two things:
  ### 1. If the condition is violated.
  ### 2. If the Shapley values are identical.
  ### If the condition is violated the symmetry property holds because of the  
  ### implication "condition => Shapley values identical" which does not give us  
  ### any information whether the Shapley values are identical in this case  
  ### (because from FALSE one can not imply anything).
  ### On the other hand, when the condition is met then the Shapley values have  
  ### to be identical. This is ensured because in this case the condition is not  
  ### violated meaning that the left hand side of the OR is FALSE. Therefore the  
  ### right hand side has to hold which checks whether the Shapley values are identical.
  all(any(payoff_diff_j != payoff_diff_k) | shapley_set(j, population) == shapley_set(k, population))
}
```

```{r}
### Check the symmetry property for all possible combinations of two players.
#### All combinations of two players.
all_combinations_two_players <- as.list(set_combn(population, m = 2))
#### The results of the application of the individual symmetry checks.
symmetry_check_all_combinations <- sapply(1:length(all_combinations_two_players),
        function(i) symmetry_check(as.list(all_combinations_two_players[[i]])[1],
                                   as.list(all_combinations_two_players[[i]])[2],
                                   population))
#### The combined result.
print(all(symmetry_check_all_combinations))
### Seems to work for our toy example.
```

### Dummy Property Check
```{r}
### Check the dummy property of the Shapley value as defined in the lecture or  
  ### in chapter 17 of Christoph Molnar's book Interpretable Machine Learning  
  ### (https://christophm.github.io/interpretable-ml-book/shapley.html#definition).
dummy_check <- function(j, population) {
  all_coalitions_without_candidate <- all_coalitions_without_members(j, population)
  
  ### Calculate the payoff differences for all possible coalitions, once including
  ### and once excluding j.
  payoff_diff_j <- payoff_diff_list(j, all_coalitions_without_candidate)
  
  ### This logical statement now checks two things:
  ### 1. If the condition is violated.
  ### 2. If the Shapley value is 0.
  ### If the condition is violated the dummy property holds because of the implication  
  ### "condition => Shapley value is 0" which does not give us any information  
  ### whether the Shapley value is 0 in this case (because from FALSE one can not  
  ### imply anything).
  ### On the other hand, when the condition is met then the Shapley value has to  
  ### be 0. This is ensured because in this case the condition is not violated  
  ### meaning that the left hand side of the OR is FALSE. Therefore the right hand  
  ### side has to hold which checks whether the Shapley value is 0.
  all(any(payoff_diff_j != 0) | shapley_set(j, population) == 0)
}
```

```{r}
### Check the dummy property for all possible players.
#### The results of the application of the individual dummy property checks.
dummy_check_all_players <- sapply(1:length(population),
                                  function(i) dummy_check(population[i],
                                                          population))
#### The combined result.
print(all(dummy_check_all_players))
### Seems to work for our toy example.
```

### Additivity Check 
```{r}
### Check the additivity property of the Shapley value as defined in the lecture  
  ### or in chapter 17 of Christoph Molnar's book Interpretable Machine Learning  
  ### (https://christophm.github.io/interpretable-ml-book/shapley.html#definition).
### Here we assume that the user is giving us two payoff functions that sum up
### to the original payoff function.
additivity_check <- function(population, payoff_func_1, payoff_func_2) {
  ### Define the combined payoff function.
  payoff_func_1_and_2 <- function(x) payoff_func_1(x) + payoff_func_2(x)
  
  ### Get all the Shapley values when using payoff_func_1 and when using  
  ### payoff_func_2.
  all_shapley_values_payoff_func_1 <- all_shapley_values(population, shapley_set, payoff_func_1)
  all_shapley_values_payoff_func_2 <- all_shapley_values(population, shapley_set, payoff_func_2)
  
  ### Get all the Shapley values when using the combined payoff function.
  all_shapley_values_payoff_func_1_and_2 <- all_shapley_values(population,
                                                               shapley_set,
                                                               payoff_func_1_and_2)
  
  ### Check if the combined Shapley value equals the sum of the Shapley values  
  ### for every member of the population (rounding is necessary here since the  
  ### values can differ because of numerical instabilities during computation).
  all(round(all_shapley_values_payoff_func_1_and_2, 5)
      == round(all_shapley_values_payoff_func_1 + all_shapley_values_payoff_func_2, 5))
}
```

```{r}
### Testing:
### Define a new payoff function (which just consists of the first three summands  
  ### of the original payoff function).
payoff_func_1 <- function(coalition) {
  ### Define boolean variables that indicate whether Timnit, Margret, Samy, Jeff  
  ### and Larry are in the set or not.
  t <- 't' %in% coalition
  s <- 's' %in% coalition
  m <- 'm' %in% coalition
  j <- 'j' %in% coalition
  l <- 'l' %in% coalition
  
  ### Definition of the overall performance.
  10*t + 10*m + 2*j
}

### Define the second payoff function accordingly (which hence consists of the  
  ### second three summands of the original payoff function).
payoff_func_2 <- function(coalition) {
  ### Define boolean variables that indicate whether Timnit, Margret, Samy, Jeff  
  ### and Larry are in the set or not.
  t <- 't' %in% coalition
  s <- 's' %in% coalition
  m <- 'm' %in% coalition
  j <- 'j' %in% coalition
  l <- 'l' %in% coalition
  
  ### Definition of the overall performance.
  20*(t & m) + 20*(t & m & s) - 30*((t | m | s) & j)
}

### Check the additivity property (at least for the above decomposition of the  
  ### original payoff function. Of course others are possible). 
additivity_check_result <- additivity_check(population, payoff_func_1, payoff_func_2)
### Show the result.
print(additivity_check_result)
### Seems to work for our toy example.
```

### Efficiency Check 
```{r}
### Check the efficiency property of the Shapley value as defined in the lecture  
  ### or in chapter 17 of Christoph Molnar´s book Interpretable Machine Learning  
  ### (https://christophm.github.io/interpretable-ml-book/shapley.html#definition).
efficiency_check <- function(population, v_function=payoff) {
  ### The left hand side gives us the total payoff of the population. On the right  
  ### hand side we sum over the Shapley values of each individual player. For the  
  ### efficiency property to hold these must be equal.
  v_function(population) == sum(all_shapley_values(population, shapley_set, v_function))
}
```

```{r}
### Check the efficiency property for the whole population.
#### The result of the application of the efficiency property check for the population.
efficiency_check_result <- efficiency_check(population)
#### Show the result.
print(efficiency_check_result)
### Seems to work for our toy example.
```

